# Generated by Django 4.0.6 on 2022-07-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('image', models.ImageField(upload_to='adverts', verbose_name='Image')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
            ],
        ),
    ]
