# Generated by Django 4.0.6 on 2022-07-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_advert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(default='photo', upload_to='adverts', verbose_name='image'),
        ),
    ]
